//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChilindoTechTest.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountDetail()
        {
            this.AccountTransactions = new HashSet<AccountTransaction>();
        }
    
        public int AccountNumber { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<Common.Enums.ChilindoCurrencyType> CurrencyType { get; set; }
        public string HolderName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountTransaction> AccountTransactions { get; set; }
    }
}
